//USER REGISTRATION
export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

//USER LOGIN
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';

//USER LOGOUT
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';

//USER PROFILE
export const USER_PROFILE_REQUEST = 'USER_PROFILE_REQUEST';
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS';
export const USER_PROFILE_FAIL = 'USER_PROFILE_FAIL';

//USER UPDATE
export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL';

// FETCH USERS
export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAIL = 'CREATE_USERS_FAIL';

//CROP

export const CREATE_CROP_REQUEST = 'CREATE_CROP_REQUEST';
export const CREATE_CROP_SUCCESS = 'CREATE_CROP_SUCCESS';
export const CREATE_CROP_FAIL = 'CREATE_CROP_FAIL';

// FETCH CROP
export const FETCH_CROP_REQUEST = 'FETCH_CROP_REQUEST';
export const FETCH_CROP_SUCCESS = 'FETCH_CROP_SUCCESS';
export const FETCH_CROP_FAIL = 'CREATE_CROP_FAIL';

//DELETE CROP
export const DELETE_CROP_REQUEST = 'DELETE_CROP_REQUEST';
export const DELETE_CROP_SUCCESS = 'DELETE_CROP_SUCCESS';
export const DELETE_CROP_FAIL = 'DELETE_CROP_FAIL';

//CROP DETAILS
export const CROP_DETAIL_REQUEST = 'CROP_DETAIL_REQUEST';
export const CROP_DETAIL_SUCCESS = 'CROP_DETAIL_SUCCESS';
export const CROP_DETAIL_FAIL = 'CROP_DETAIL_FAIL';

//UPDATE CROP
export const CROP_UPDATE_REQUEST = 'CROP_UPDATE_REQUEST';
export const CROP_UPDATE_SUCCESS = 'CROP_UPDATE_SUCCESS';
export const CROP_UPDATE_FAIL = 'CROP_UPDATE_FAIL';